### PR TITLE
Removing facebook profile upon signup and no longer sets country automatically

### PR DESCRIPTION
**Pull request by daniel-marklund**

### CODE REVIEW

**Comment by jongotlin** [comment]
Thanks for your PR. The optional country is however not correct. Modify the form type with [empty_data](http://symfony.com/doc/current/reference/forms/types/choice.html#empty-data) rather than adding a country without name.

**Comment by jongotlin** [comment]
Did you have the time to look into this?

**Comment by mikaelohren** [comment]
@jongotlin, if I want another developer to take over Daniels code and fix it, how that dev do that?

**Comment by jongotlin** [comment]
@mikaelohren It's not much to inherit just just start over. Ask the other dev to make a separate pr for each task (FB removal in one and no default country in one).

**Comment by mikaelohren** [comment]
Let's close this PR since it is already fixed.

**Pull request closed without merging**
