### PR TITLE
Lower case on interests in match email

### PR DESCRIPTION
**Pull request by MintL**

### CODE REVIEW

**Comment by MintL** [comment]
Why does the check fail, I have barely changed anything?

**Comment by jongotlin** [comment]
For some reason phpunit is missing. Can you add it by running `composer require --dev phpunit/phpunit:"^5.6"`?

**Comment by MintL** [comment]
Still failed after running the command

**Comment by jongotlin** [comment]
Finally! :tada: It was some issues with how Travis was configured. 
Thanks.

**Comment by MintL** [comment]
Finally yes! :) but why did it cause problems in this branch?

**Comment by jongotlin** [comment]
I guess Travis changed how Phpunit was working just recently.

**Pull request merged**
