### PR TITLE
New admin workflow

### PR DESCRIPTION
**Pull request by rifeman2007**

### CODE REVIEW

**Comment by jongotlin** [comment]
Please revert the the merge. I want to look through it first. For example you need to add migrations.

**Comment by rifeman2007** [comment]
Not sure why we still need to add a migration since we already have a command to update the db fields.

**Comment by jongotlin** [comment]
We want one way to deploy. And maybe there is more in this huge pr.

**Comment by mikaelohren** [comment]
This is my fault. We will do a new PR and @jongotlin you can do a code review.

**Pull request merged**
