### PR TITLE
Moved category names to twig extension

### PR DESCRIPTION
**Pull request by rifeman2007**

### CODE REVIEW

**Comment by jongotlin** [comment]
You have to use `admin-2`-branch as origin.

**Comment by rifeman2007** [comment]
I have been working on admin_2.0 from the start. I will just merge my work from that branch

**Comment by jongotlin** [comment]
That branch is dead since it got merged and reverted. Just cherry pick your commits to the open Admin 2 pr #86.

**Comment by jongotlin** [comment]
Also, it's easier if you use Kompisbyran's repo directly rather than your fork.

**Comment by rifeman2007** [comment]
Yeah, I will use the repo directly because it seems that my old changes were lost from admin_2.0 branch during the reverting. I will have to cherry pick them to admin-2 branch.

**Pull request merged**
